### ISSUE TITLE
FastCGI on Lua 5.3

### ISSUE THREAD

**Issue by xspager** [keplerproject/wsapi#39]
Hi! I'm able to install with luarocks the package wsapi-fcgi using Lua 5.3 but if I call cgilua's cgilua.fcgi i get `lib/lua/5.3/lfcgi.so: undefined symbol: luaL_optlong`

**Comment by ignacio** [comment]
Can you give this a go, installing with:

    luarocks search wsapi-fcgi cvs-2 --server=http://luarocks.org/manifests/mascarenhas

**Comment by xspager** [comment]
Ok, this change fixed the problem but cgilua is using the function module() in some places, if I'm not mistaken it is deprecated on 5.3(?). Thanks a lot! :)

**Comment by xspager** [comment]
ops! the last version of CGILua already fix the compatibility with Lua 5.3

**Comment by ignacio** [comment]
Yes. No new release yet that contains those changes. Can you confirm if it is working for you?

**Comment by xspager** [comment]
Yes, once again, thanks!

**Comment by ignacio** [comment]
Great :) I'll be closing this for now, thanks for getting back to me.
I think we're due for a release soon (tm).
