### ISSUE TITLE
Update Luarock

### ISSUE THREAD

**Issue by CodelessFuture** [keplerproject/wsapi#43]
Can I ask you to update the luarockt for this project, please?

I'm sorry I did not explain myself. I'm Massimiliano Bertinetti and I'm the new lead developer of Sailor. By applying the master branches of the packages on which sailor depends I managed to put into production Sailor with Lua 5.3. If published on Luarocks I can also update Sailor with new dependencies and allow Sailor users to use Lua 5.3 with Sailor 0.6.0. Thank you!

**Comment by CodelessFuture** [comment]
I need your help so that I can publish Sailor 0.6.0 with Luarocks working out of the box with Lua 5.3.
Cgilua, Wsapi and Coxpcall need to be update with master on luarocks.

**Comment by hishamhm** [comment]
@mascarenhas I just pushed updated rockspecs and a tag for release 1.7, including Lua 5.3 support. Can you `luarocks upload` the new rockspecs, since `wsapi` is under your account?

**Comment by mascarenhas** [comment]
Rocks for `wsapi`, `wsapi-fcgi`, and `wsapi-xavante` updated at luarocks.org. Thanks @hishamhm!

**Comment by CodelessFuture** [comment]
Thank you very much! I need only cgilua update!
